#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly COMPOSE_FILE="${PROJECT_DIR}/docker-compose.yml"
readonly ROUTE_FILE="${PROJECT_DIR}/caddy/sites/phase8-integration.Caddyfile"
readonly TEST_HOST="phase8.run.sakala.localhost"
RESPONSE_FILE=""

caddy_was_running=false
if [[ "$(docker inspect --format '{{.State.Running}}' sakala-caddy 2>/dev/null || true)" == "true" ]]; then
    caddy_was_running=true
fi

cleanup() {
    rm -f "${ROUTE_FILE}"

    if [[ -n "${RESPONSE_FILE}" ]]; then
        rm -f "${RESPONSE_FILE}"
    fi

    if [[ "$(docker inspect --format '{{.State.Running}}' sakala-caddy 2>/dev/null || true)" == "true" ]]; then
        docker exec sakala-caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1 || true
    fi

    if [[ "${caddy_was_running}" == "false" ]]; then
        docker compose --project-directory "${PROJECT_DIR}" -f "${COMPOSE_FILE}" down --remove-orphans >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT

"${SCRIPT_DIR}/create-network.sh"
docker compose --project-directory "${PROJECT_DIR}" -f "${COMPOSE_FILE}" up -d --build

printf '%s\n' \
    '# Generated by the Phase 8 integration test.' \
    "${TEST_HOST}:80 {" \
    $'\treverse_proxy sakala-demo-static:8080' \
    '}' >"${ROUTE_FILE}"

docker exec sakala-caddy caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
docker exec sakala-caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile

published_address="$(docker compose --project-directory "${PROJECT_DIR}" -f "${COMPOSE_FILE}" port caddy 80)"
readonly HTTP_PORT="${published_address##*:}"
RESPONSE_FILE="$(mktemp)"
readonly RESPONSE_FILE

for _attempt in {1..20}; do
    if curl --fail --silent --show-error \
        --header "Host: ${TEST_HOST}" \
        "http://127.0.0.1:${HTTP_PORT}" >"${RESPONSE_FILE}"; then
        break
    fi
    sleep 1
done

grep -q "Aplikasi demo Sakala berjalan" "${RESPONSE_FILE}"

rm -f "${ROUTE_FILE}"
docker exec sakala-caddy caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
docker exec sakala-caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
curl --fail --silent --show-error \
    --header "Host: ${TEST_HOST}" \
    "http://127.0.0.1:${HTTP_PORT}" | grep -q "Sakala Edge is running"

rm -f "${RESPONSE_FILE}"
echo "Phase 8 runtime route integration passed."
